---
name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build
        run: |
          go build -v ./...

      - name: Tag
        run: |
          if ! [[ ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "tag needs to be x.y.z, e.g. 1.2.3"
            exit 1
          fi
          git tag v${{ github.event.inputs.tag }}
          git push origin v${{ github.event.inputs.tag }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ github.event.inputs.tag }}
          tag_name: v${{ github.event.inputs.tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: false
